name = "hand-api"
version = "1.0.0"
wasm = "party.wasm"
wasm_sha256 = "d902c2e03941773ad8d11520b7cf8f9f7adbd5981c704691dce8be59ae75b870"

provides = []
consumes = ["orchestrator.dispatch"]
depends_on = ["lua-orchestrator"]

capabilities = [
    "transport.http.inbound",
    "entropy.read",
]

[config]
jwt_secret = "dev-jwt-secret-change-me"
service_token = "dev-service-token-change-me"
